---
- name: Configure time sync with chrony
  hosts: all
  become: yes

  vars:
    ntp_servers:
      - time.google.com
      - time.cloudflare.com

    chrony_conf_path: >-
      {{ '/etc/chrony.conf'
         if ansible_facts['os_family'] == 'RedHat'
         else '/etc/chrony/chrony.conf' }}

    chrony_service: >-
      {{ 'chronyd'
         if ansible_facts['os_family'] == 'RedHat'
         else 'chrony' }}

  tasks:
    - name: Install chrony
      package:
        name: chrony
        state: present

    - name: Remove existing server lines
      lineinfile:
        path: "{{ chrony_conf_path }}"
        regexp: '^server'
        state: absent

    - name: Add NTP servers
      lineinfile:
        path: "{{ chrony_conf_path }}"
        line: "server {{ item }} iburst"
        insertafter: EOF
      loop: "{{ ntp_servers }}"

    - name: Enable and restart chrony service
      systemd:
        name: "{{ chrony_service }}"
        state: restarted
        enabled: yes

