---
- name: Rocky Linux Nginx ModSecurity Source Build (ONLY)
  hosts: ansible_r
  become: yes

  tasks:

    # 1. 필수 의존성 라이브러리 설치 (dnf groupinstall 및 개별 패키지)
    - name: Install EPEL release 
      dnf :
        name: epel-release
        state: present

    # 2. CRB 저장소 활성화
    - name: Enable CRB repositroty
      shell: |
        dnf config-manager --set-enabled crb

    # 3. 필수 의존성 라이브러리 설치 (이제 정상적으로 찾아집니다)
    - name: Install Development Tools and Dependencies
      dnf:
        name:
          - "@Development Tools"
          - git
          - gd-devel
          - perl-ExtUtils-Embed
          - libcurl-devel
          - openssl-devel
          - pcre-devel
          - libxml2-devel
          - yajl-devel        # 이제 crb에서 찾음
          - lua-devel         # 이제 crb에서 찾음
          - lmdb-devel        # 이제 crb에서 찾음
          - libtool
          - autoconf
          - libmaxminddb-devel # 이제 crb에서 찾음
          - wget
        state: present

    # 4. ModSecurity 설치
    - name: Clone ModSecurity v3
      git:
        repo: https://github.com/SpiderLabs/ModSecurity
        dest: /opt/ModSecurity #/opt 폴더는 있지만 ModSecurity폴더가 없어도 자동생성
        version: v3/master
        depth: 1
        recursive: yes
        # git clone을 하고 자동으로 git submodule을 하고 update --init --recursive 실행함

    # 5. ModSecurity 빌드  
    - name: Build and Install Libmodsecurity
      shell: |
        ./build.sh
        ./configure
        make -j$(nproc)
        make install
      args: # shell명령 실행 이전에 먼저 실행되는 환경 값 
        chdir: /opt/ModSecurity
        creates: /usr/local/modsecurity/lib/libmodsecurity.so
        # 사전검사 creates로 위의 파일이 있다면 shell 명령어를 실행하지 않음.
        # 그리고 빌드를 하면 저 폴더에 libmodsecurity.so가 생김.

    # 6. ModSecurity-nginx 가져오기1 + 버전 확인
    - name: Get Nginx version
      shell: nginx -v 2>&1 | cut -d '/' -f 2
      register: nginx_ver #위의 shell결과를nginx_ver  변수로 등록하겠다.
      changed_when: false #확인만 했으니까 변경은 반영하지 않겠다.

    - name: Get ModSecurity-nginx by nignx -v
      get_url:
        url: "http://nginx.org/download/nginx-{{ nginx_ver.stdout }}.tar.gz"
        dest: "/opt/nginx-{{ nginx_ver.stdout }}.tar.gz"

    # 7.  ModSecurity-nginx 가져오기2
    - name: Get ModSecurity-nginx by clon
      git:
        repo: https://github.com/SpiderLabs/ModSecurity-nginx.git
        dest: /opt/ModSecurity-nginx
        depth: 1

    # 8. 동적 모듈(.so) 컴파일 및 복사
    - name: Compile ModSecurity Module
      shell: |
        tar zxvf nginx-{{ nginx_ver.stdout }}.tar.gz
        cd nginx-{{ nginx_ver.stdout }}/
        ./configure --with-compat --add-dynamic-module=../ModSecurity-nginx
        make modules
        cp objs/ngx_http_modsecurity_module.so /usr/share/nginx/modules/
      args:
        chdir: /opt
        creates: /usr/share/nginx/modules/ngx_http_modsecurity_module.so

    # 9. Nginx 설정 파일 수정 (모듈 로드 및 IPS 설정)
    - name: Load ModSecurity Module in nginx.conf
      lineinfile:
        path: /etc/nginx/nginx.conf
        insertbefore: BOF
        line: "load_module modules/ngx_http_modsecurity_module.so;"

    - name: Create ModSec directories and copy configs
      shell: |
        mkdir -p /etc/nginx/modsec
        cp /opt/ModSecurity/modsecurity.conf-recommended /etc/nginx/modsec/modsecurity.conf
        cp /opt/ModSecurity/unicode.mapping /etc/nginx/modsec/

    - name: Set ModSecurity to IPS Mode (On)
      lineinfile:
        path: /etc/nginx/modsec/modsecurity.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^SecRuleEngine', line: 'SecRuleEngine On' }
        - { regexp: '^SecRequestBodyAccess', line: 'SecRequestBodyAccess On' }
        - { regexp: '^SecAuditEngine', line: 'SecAuditEngine On' }

    # 10. OWASP CRS 설정 및 메인 설정 파일 생성
    - name: Clone OWASP CRS
      git:
        repo: https://github.com/coreruleset/coreruleset.git
        dest: /etc/nginx/modsec/coreruleset

    - name: Setup main.conf and CRS config
      shell: |
        cp /etc/nginx/modsec/coreruleset/crs-setup.conf.example /etc/nginx/modsec/crs-setup.conf
        echo 'Include /etc/nginx/modsec/modsecurity.conf' > /etc/nginx/modsec/main.conf
        echo 'Include /etc/nginx/modsec/crs-setup.conf' >> /etc/nginx/modsec/main.conf
        echo 'Include /etc/nginx/modsec/coreruleset/rules/*.conf' >> /etc/nginx/modsec/main.conf

    - name: Apply ModSecurity to Nginx default server block
      blockinfile:
        path: /etc/nginx/nginx.conf
        insertafter: 'http {'
        block: |
                modsecurity on;
                modsecurity_rules_file /etc/nginx/modsec/main.conf;

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
