---
- name: Fix and Deploy Suricata (Clean Install)
  hosts: all
  become: yes
  tasks:

    # 1. 실제 인터페이스 감지
    - name: Get primary interface
      shell: "ip -o link show | awk -F': ' '$2 != \"lo\" {print $2; exit}'"
      register: iface_result

    - name: Set interface fact
      set_fact:
        real_iface: "{{ iface_result.stdout }}"

    # 2. 깨진 설정 파일 삭제 및 재설치 (초기화)
    - name: Reset Suricata config (Rocky)
      shell: dnf reinstall suricata -y
      when: ansible_distribution == "Rocky"

    - name: Reset Suricata config (Ubuntu)
      shell: apt-get install --reinstall suricata -y
      when: ansible_distribution == "Ubuntu"

    # 3. 필수 경로 및 빈 룰 생성
    - name: Ensure rule directory and file exist
      file:
        path: /var/lib/suricata/rules/suricata.rules
        state: touch
        mode: '0644'

    # 4. ★ 핵심: 깨끗한 설정 파일 배포
    # (위 1번에서 만든 j2 파일을 서버로 전송합니다)
    - name: Deploy clean suricata.yaml
      template:
        src: suricata.yaml.j2
        dest: /etc/suricata/suricata.yaml
        mode: '0644'

    # 5. 설정 검증
    - name: Validate Suricata Config
      command: suricata -T -c /etc/suricata/suricata.yaml
      register: test_out
      failed_when: test_out.rc != 0

    # 6. 서비스 시작
    - name: Restart Suricata
      systemd:
        name: suricata
        state: restarted
        enabled: yes

